apiVersion: v1
kind: ServiceAccount
metadata:
  name: testing-prometheus-server
  namespace: monitoring
  annotations:
    test: test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testing-prometheus-server
  namespace: monitoring
spec:
  template:
    metadata:
      annotations:
        test: test
    spec:
      containers:
        - name: prometheus-server
          env:
            - name: PROMETHEUS_URL
              value: "https://prometheus.overlay.aws.example.com"
