apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  service: monitoring
resources:
  - prometheus.yaml
#images:
#  - name: prometheus
#    newName: prom/prometheus
#    newTag: v2.33.4
