apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base/
resources:
  - prometheus-ingress.yaml
patchesStrategicMerge:
  - prometheus.yaml
secretGenerator:
  # description: credentials for access to object storage
  # used-by: Prometheus, Thanos Store, Thanos Compact
  - name: thanos-storage
    type: Opaque
    files:
      - credentials.json=secrets/credentials.json
configMapGenerator:
  # description: application alerts handled by thanos-rule
  # used-by: Thanos Rule
  - name: alerts
    files:
      - prometheus-alerts.yaml=resources/prometheus-alerts.yaml
  # description: Prometheus configuration
  # used-by: Prometheus
  - name: prometheus
    files:
      - prometheus.yaml.tmpl=resources/prometheus.yaml.tmpl
