apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./prometheus
  - ./grafana

images:
- name: quay.io/prometheus/prometheus
  newTag: v2.31.0

replicas:
- name: testing-grafana
  count: 3

commonLabels:
  service: monitoring
